### ISSUE TITLE
(Renamed) Add checks for encrypted webhooks 

### ISSUE THREAD

**Issue by 3000IQPlay** [mindlesslydev/AntiRat#5]
How did this "AntiRat" thing that isnt even AntiRat got 3 stars

**Comment by master7720** [comment]
Fr lol

**Comment by mindlesslydev** [comment]
You know there are checks for things other than webhooks right? When you say it can’t detect anything, that is just clearly inaccurate. As far as encrypted webhooks are concerned, good suggestion. Don’t expect a tool in its 0.1 release to be perfect lol

**Comment by master7720** [comment]
> You know there are checks for things other than webhooks right? When you say it can’t detect anything, that is just clearly inaccurate. As far as encrypted webhooks are concerned, good suggestion. Don’t expect a tool in its 0.1 release to be perfect lol

doesnt really matter this is very bad LOL

**Comment by master7720** [comment]
This cant even detect Encrypted Webhook LMAO + not every webhook is a rat btw (But most of them are) + not every rat uses webhook + get Sentinel for this + Nobody uses this + it cant detect anything + all this is true + ratio (change the name back bozo)

**Comment by mindlesslydev** [comment]
> > You know there are checks for things other than webhooks right? When you say it can’t detect anything, that is just clearly inaccurate. As far as encrypted webhooks are concerned, good suggestion. Don’t expect a tool in its 0.1 release to be perfect lol
> 
> doesnt really matter this is very bad LOL

you have no legitimate criticisms and realistically this is a non issue as the embed will be detected anyway. closing as you are being a moron

**Comment by master7720** [comment]
> > > You know there are checks for things other than webhooks right? When you say it can’t detect anything, that is just clearly inaccurate. As far as encrypted webhooks are concerned, good suggestion. Don’t expect a tool in its 0.1 release to be perfect lol
> > 
> > 
> > doesnt really matter this is very bad LOL
> 
> you have no legitimate criticisms and realistically this is a non issue as the embed will be detected anyway. closing as you are being a moron

moron? your the moron thinking this will work LOL

**Comment by fireguy188** [comment]
@master7720 you are a moron + 99% of the time there's a webhook it's a rat + mindlessly just said there are other checks + it definitely does detect rats

**Comment by master7720** [comment]
> @master7720 you are a moron + 99% of the time there's a webhook it's a rat + mindlessly just said there are other checks + it definitely does detect rats

Hope you know a webhook isnt a rat….

**Comment by master7720** [comment]
hush mode
