### ISSUE TITLE
Useless? Misleading? Bad code?

### ISSUE THREAD

**Issue by IThundxr** [mindlesslydev/AntiRat#8]
Im doing this pretty quick but ofc as you know this cant find all rats its pretty bad pretty useless brings false hope and said by skytils dev this is pretty shit 
```
addEmbed
func_148254_d
func_111286_b
discord.com/api/webhooks
launcher_profiles.json
media.guilded.gg/webhooks/
checkip.amazonaws
Branchlock Demo
```

those checks are pretty bad have you even check real rats? and bro this code is so bad better option redo this repo into educating people how to not get ratted etc like @ILikePlayingGames https://github.com/ILikePlayingGames/SkyblockModSafety repo which is great please dont try to get people to download a useless mod

**Comment by mindlesslydev** [comment]
Fuck off

**Comment by mindlesslydev** [comment]
Sorry for being rude but if people are going to bring up the same broken arguments I really am not going to stand for the harassment any longer

**Comment by master7720** [comment]
> Fuck off

xDD

**Comment by master7720** [comment]
> Fuck off

i see you cant handle the truth?

**Comment by IThundxr** [comment]
> > Fuck off
> 
> i see you cant handle the truth?

he cant lol
